<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sanket" failures="1" tests="2" name="Test" time="7.743" errors="0" timestamp="2024-06-19T12:32:16 IST">
  <testcase classname="TestClasses.CheckAccountCreation" name="checkCreatAccountButtonIsEnabled" time="1.209"/>
  <testcase classname="TestClasses.CheckAccountCreation" name="checkEmailErrorMessage" time="1.412">
    <failure type="java.lang.AssertionError" message="not get proper message expected [An account with this email already exists on Zomato. Please login to verify your lasfkj.] but found [An account with this email already exists on Zomato. Please login to verify your account.]">
      <![CDATA[java.lang.AssertionError: not get proper message expected [An account with this email already exists on Zomato. Please login to verify your lasfkj.] but found [An account with this email already exists on Zomato. Please login to verify your account.]
at TestClasses.CheckAccountCreation.checkEmailErrorMessage(CheckAccountCreation.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkEmailErrorMessage -->
</testsuite> <!-- Test -->
