<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-20T12:20:10 IST" name="Default suite" finished-at="2024-06-20T12:20:19 IST" duration-ms="9441">
    <groups>
    </groups>
    <test started-at="2024-06-20T12:20:10 IST" name="Default test" finished-at="2024-06-20T12:20:19 IST" duration-ms="9441">
      <class name="TestClasses.CheckAccountCreationTest">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:TestClasses.CheckAccountCreationTest@7f3b84b8]" started-at="2024-06-20T12:20:10 IST" name="openBrowser" finished-at="2024-06-20T12:20:11 IST" duration-ms="1619" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="createPomObject()[pri:0, instance:TestClasses.CheckAccountCreationTest@7f3b84b8]" started-at="2024-06-20T12:20:11 IST" name="createPomObject" finished-at="2024-06-20T12:20:11 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPomObject -->
        <test-method is-config="true" signature="openWebSite()[pri:0, instance:TestClasses.CheckAccountCreationTest@7f3b84b8]" started-at="2024-06-20T12:20:11 IST" name="openWebSite" finished-at="2024-06-20T12:20:14 IST" duration-ms="2585" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openWebSite -->
        <test-method signature="checkCreatAccountButtonIsEnabled()[pri:0, instance:TestClasses.CheckAccountCreationTest@7f3b84b8]" started-at="2024-06-20T12:20:14 IST" name="checkCreatAccountButtonIsEnabled" finished-at="2024-06-20T12:20:16 IST" duration-ms="1908" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkCreatAccountButtonIsEnabled -->
        <test-method is-config="true" signature="openWebSite()[pri:0, instance:TestClasses.CheckAccountCreationTest@7f3b84b8]" started-at="2024-06-20T12:20:16 IST" name="openWebSite" finished-at="2024-06-20T12:20:17 IST" duration-ms="1445" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openWebSite -->
        <test-method signature="checkEmailErrorMessage()[pri:0, instance:TestClasses.CheckAccountCreationTest@7f3b84b8]" started-at="2024-06-20T12:20:17 IST" name="checkEmailErrorMessage" finished-at="2024-06-20T12:20:19 IST" duration-ms="1841" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[not get proper message expected [An account with this email already exists on Zomato. Please login to verify your lasfkj.] but found [An account with this email already exists on Zomato. Please login to verify your account.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: not get proper message expected [An account with this email already exists on Zomato. Please login to verify your lasfkj.] but found [An account with this email already exists on Zomato. Please login to verify your account.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at TestClasses.CheckAccountCreationTest.checkEmailErrorMessage(CheckAccountCreationTest.java:82)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkEmailErrorMessage -->
      </class> <!-- TestClasses.CheckAccountCreationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
